language: cpp
dist: trusty
sudo: true
matrix:
    include:
#        -   os: linux
#            compiler: gcc
#            addons: &gcc6
#                apt:
#                    sources: ['ubuntu-toolchain-r-test']
#                    packages:
#                        - 'g++-7'
#                        - 'libboost-dev'
#            env: C_COMPILER='gcc-7' CXX_COMPILER='g++-7'
        -   os: linux
            compiler: clang
            addons: &clang40
                apt:
                    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
                    packages:
                        - 'libstdc++-7-dev'
                        - 'clang-5.0'
                        - 'libboost-dev'
            env: C_COMPILER='clang-5.0' CXX_COMPILER='clang++-5.0'
before_install:
    - sudo apt-get update
before_script:
    - export CC=${C_COMPILER}
    - export CXX=${CXX_COMPILER}
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -Wdev ..
    - cmake --build .
script:
    - cd ${TRAVIS_BUILD_DIR}/build
    - ./cgs-test
notifications:
    email:
        on_success: change
        on_failure: change
