language: cpp
dist: trusty
sudo: true
matrix:
    include:
#        -   os: linux
#            compiler: gcc
        -   os: linux
            compiler: clang
            env: C_COMPILER='clang-5.0' CXX_COMPILER='clang++-5.0'
before_install:
    - sudo add-apt-repository ppa::ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa::llvm-toolchain-trusty-5.0 -y
    - sudo apt-get update
    - sudo apt-get install libboost-dev g++-7 libstdc++-7-dev clang-5.0
before_script:
    - export CC=${C_COMPILER}
    - export CXX=${CXX_COMPILER}
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -Wdev ..
    - cmake --build .
script:
    - cd ${TRAVIS_BUILD_DIR}/build
    - ./cgs-test
notifications:
    email:
        on_success: change
        on_failure: change
